### ISSUE TITLE
Stratum Source Build Fails Due to Go Related Error

### ISSUE THREAD

**Issue by masesk** [stratum/stratum#1103]
**Describe the bug**
Stratum fails to build when cloning and building on a new system with a Go related issue.

**Environment**
Please Note: I have previously built Stratum on the exact same environment with no errors or issues.

- WSL 2 running Ubuntu 22.04
- Ubuntu clang version 14.0.0-1ubuntu1.1
- bazel 4.2.3

If building from source:
`bazel version`
bazel 4.2.3

**To Reproduce**
1. Clone Stratum on main, expunge any previous dependencies with `bazel clean --expunge`
2. Run this command `bazel build //stratum/hal/bin/dummy:stratum_dummy --sandbox_debug --verbose_failures`
3. See the error below:

```
ERROR: /home/user/.cache/bazel/_bazel_user/222cade390d2e9be9ec3a02be0f4ca7e/external/org_golang_google_grpc/internal/syscall/BUILD.bazel:3:11: GoCompilePkg external/org_golang_google_grpc/internal/syscall/go_default_library.a [for host] failed: (Exit 1): linux-sandbox failed: error executing command
  (cd /home/user/.cache/bazel/_bazel_user/222cade390d2e9be9ec3a02be0f4ca7e/sandbox/linux-sandbox/537/execroot/com_github_stratum_stratum && \
  exec env - \
    CGO_ENABLED=1 \
    GOARCH=amd64 \
    GOOS=linux \
    GOPATH='' \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=/usr/bin:/bin \
    TMPDIR=/tmp \
  /home/user/.cache/bazel/_bazel_user/install/ec7bc80570c57e35507fafa6aadd57b1/linux-sandbox -t 15 -w /home/user/.cache/bazel/_bazel_user/222cade390d2e9be9ec3a02be0f4ca7e/sandbox/linux-sandbox/537/execroot/com_github_stratum_stratum -w /tmp -w /dev/shm -D -- bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src external/org_golang_google_grpc/internal/syscall/syscall_linux.go -src external/org_golang_google_grpc/internal/syscall/syscall_nonlinux.go -arc 'google.golang.org/grpc/grpclog=google.golang.org/grpc/grpclog=bazel-out/host/bin/external/org_golang_google_grpc/grpclog/go_default_library.x' -importpath google.golang.org/grpc/internal/syscall -p google.golang.org/grpc/internal/syscall -package_list bazel-out/host/bin/external/go_sdk/packages.txt -o bazel-out/host/bin/external/org_golang_google_grpc/internal/syscall/go_default_library.a -x bazel-out/host/bin/external/org_golang_google_grpc/internal/syscall/go_default_library.x -gcflags '' -asmflags '')
compilepkg: missing strict dependencies:
        /home/user/.cache/bazel/_bazel_user/222cade390d2e9be9ec3a02be0f4ca7e/sandbox/linux-sandbox/537/execroot/com_github_stratum_stratum/external/org_golang_google_grpc/internal/syscall/syscall_linux.go: import of "golang.org/x/sys/unix"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
1699514216.064196011: src/main/tools/linux-sandbox-pid1.cc:423: wait returned pid=2, status=0x100
1699514216.064212211: src/main/tools/linux-sandbox-pid1.cc:441: child exited normally with code 1
1699514216.064639911: src/main/tools/linux-sandbox.cc:233: child exited normally with code 1
Target //stratum/hal/bin/dummy:stratum_dummy failed to build
ERROR: /home/user/.cache/bazel/_bazel_user/222cade390d2e9be9ec3a02be0f4ca7e/external/com_github_openconfig_hercules/BUILD.bazel:45:14 Middleman _middlemen/@com_Ugithub_Uopenconfig_Uhercules_S_S_Copenconfig_Uproto-BazelCppSemantics_build_arch_k8-fastbuild failed: (Exit 1): linux-sandbox failed: error executing command
  (cd /home/user/.cache/bazel/_bazel_user/222cade390d2e9be9ec3a02be0f4ca7e/sandbox/linux-sandbox/537/execroot/com_github_stratum_stratum && \
  exec env - \
    CGO_ENABLED=1 \
    GOARCH=amd64 \
    GOOS=linux \
    GOPATH='' \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=/usr/bin:/bin \
    TMPDIR=/tmp \
  /home/user/.cache/bazel/_bazel_user/install/ec7bc80570c57e35507fafa6aadd57b1/linux-sandbox -t 15 -w /home/user/.cache/bazel/_bazel_user/222cade390d2e9be9ec3a02be0f4ca7e/sandbox/linux-sandbox/537/execroot/com_github_stratum_stratum -w /tmp -w /dev/shm -D -- bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src external/org_golang_google_grpc/internal/syscall/syscall_linux.go -src external/org_golang_google_grpc/internal/syscall/syscall_nonlinux.go -arc 'google.golang.org/grpc/grpclog=google.golang.org/grpc/grpclog=bazel-out/host/bin/external/org_golang_google_grpc/grpclog/go_default_library.x' -importpath google.golang.org/grpc/internal/syscall -p google.golang.org/grpc/internal/syscall -package_list bazel-out/host/bin/external/go_sdk/packages.txt -o bazel-out/host/bin/external/org_golang_google_grpc/internal/syscall/go_default_library.a -x bazel-out/host/bin/external/org_golang_google_grpc/internal/syscall/go_default_library.x -gcflags '' -asmflags '')
INFO: Elapsed time: 315.035s, Critical Path: 32.20s
INFO: 697 processes: 167 internal, 530 linux-sandbox.
FAILED: Build did NOT complete successfully
```

**Expected behavior**
Stratum to build

**Comment by kapiladhikesavalu** [comment]
Seeing the same issue last couple of days. Something is broken in the build.

**Comment by bocon13** [comment]
This issue was unfortunately caused by a set of upstream changes in the golang library repos:
https://github.com/golang/text/commit/6c97a165dd661335ff7bce6104a008558123c353
https://github.com/golang/net/commit/d23d9bc549229fd1a9d375dc91141fcf1385d257
https://github.com/golang/sys/commit/1bfbee0e20e3039533666df89a91c1876e67605d

Basically, we are using an old version of go (1.15.7), and we can no longer build some go deps because the compiler thinks there are multiple packages in the same folder after the build directive changes (specifically, dropping `// +build gc`). 

Unfortunately, I don't know when I'll have the time to fix this and test everything, but here's what I'd recommend:

- Update the go version to at least 1.18 or newer
- The Go toolchain is handled by a tool called gazelle (not whatever you have installed locally), so we probably need to get a newer `gazelle` and `rules_go`: https://github.com/stratum/stratum/blob/263affc8822f04ff53f34936af8d05a28665f15a/bazel/rules/build_tools.bzl#L11-L25
https://github.com/stratum/stratum/blob/263affc8822f04ff53f34936af8d05a28665f15a/WORKSPACE#L85-L93
- Newer versions of gazelle may require a new version of bazel or not.
https://github.com/stratum/stratum/blob/263affc8822f04ff53f34936af8d05a28665f15a/.bazelversion#L1

Hopefully, this doesn't turn into too deep of a rabbit hole... but I would expect that there might be some cascading dependency updates required as we start to push versions forward. 

![Whack A Mole](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbnJnbmdvam5waWlpa3YwNGZ2ZHFyanQ4dnI0ajM2emdvODdzdzg2MCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ebITvSXYKNvRm/giphy.gif)

**Comment by masesk** [comment]
A quick fix was to override the Go modules grpc was specifically using _after_ loading the grpc_dependencies() in the WORKSPACE file.

https://github.com/masesk/stratum/blob/77891a2d8e6479a8b9cef12a057ad1d1d4f5c464/WORKSPACE#L99-L118
```
go_repository(
    name = "org_golang_x_net",
    importpath = "golang.org/x/net",
    sum = "h1:hZ/3BUoy5aId7sCpA/Tc5lt8DkFgdVS2onTpJsZ/fl0=",
    version = "v0.1.0",
)

go_repository(
    name = "org_golang_x_text",
    importpath = "golang.org/x/text",
    sum = "h1:g61tztE5qeGQ89tm6NTjjM9VPIm088od1l6aSorWRWg=",
    version = "v0.3.0",
)

go_repository(
    name = "org_golang_x_sys",
    importpath = "golang.org/x/sys",
    sum = "h1:eG7RXZHdqOJ1i+0lgLgCpSXAp6M3LYlAo6osgSi0xOM=",
    version = "v0.5.0",
)

```


This seems to temporarily fix the problem but there is an underlying issue of outdated dependencies and tools versions.
If this is the preferred solution, I can open a PR for it.
