### ISSUE TITLE
What is the correct behavior for stratum when restarts？

### ISSUE THREAD

**Issue by lxlmummy** [stratum/stratum#285]
I have successfully run stratum in Tofino equipment. Now, when stratum starts，it may use FLAGS_forwarding_pipeline_configs_file to push the last saved PipelineConfig (which includes p4info and bin/json)  to  device. 
My question is,
First, why stratum just persists PipelineConfig，why not persists entries, like table entry which may install by P4Runtime Write RPC?
Second，If no place to persists entries, after the device reboot, the previous table entries no longer exist. How can device works well like before？Or, you ask the controller like ONOS to reinstall the table entries? 
Third, acoording to https://p4.org/p4runtime/spec/master/P4Runtime-Spec.html#sec-restarts , it seems after restart, all state is reset, that means no entries, no PipelineConfig. That means each time a device is restarted, all controllers connected to the device have to reinstall the p4runtime related PipelineConfig and enties？ Is this reasonable or did I get it wrong?

**Comment by pudelkoM** [comment]
> why not persists entries

Because that is a lot more complex than it seems on the surface. Storing and replaying the whole write log has little overhead at runtime, but requires unbounded storage and can take minutes to replay with long logs. Creating a snapshot on every write increases the overhead at runtime. The only option I see, is relying on the hardware and doing a warmboot on restart to keep the old state. Warmboot is on the roadmap, but no priority at the moment.

> Or, you ask the controller like ONOS to reinstall the table entries?

Yes. The SDN way is to have dumb switches and smart controllers. There are many more causes for restarts than planed ones with the state saved (hard crash, device replacement), so that the controller cannot make any assumptions about the forwarding state anyway. It always has to recheck by reading the current state and correcting the difference.

> all controllers connected to the device have to reinstall the p4runtime related PipelineConfig and enties

Yes, no assumptions about state. `PushForwadingPipelineConfig` will be a noop if it's the same.

If you don't want to save (and restore) the latest pipeline config, setting `-forwarding_pipeline_configs_file=/dev/null` will work.

**Comment by lxlmummy** [comment]
@pudelkoM，Thank you for your detailed answers in time！Yes, storing every entry does have the potential to consume a lot of space and even affect performance. I am looking forward to your warmboot support with stratum. Just close this issue.

**Comment by lxlmummy** [comment]
@pudelkoM, I rethought the question. Is it possible that I just save the last  snapshot of write operation of table entrie instead of creating a snapshot on every write increases. For example, if controls add entry “a = 1”, and then"a=2"，I just save the “a=2” latest.  If controls first add entry "a=1",and then delete entry “a=1”, the result is no need to save. In this way, we need the amount of storage less, and the total entry the devices supported can be estimated. 
So, the question is，is it possible for stratum to just persist the latest snapshot to rebuild all entries correct after rebooting?

**Comment by pudelkoM** [comment]
Technically yes. But we have no code for that use case and no resources to implement that.
