### ISSUE TITLE
gNMI Get fails with DEADLINE_EXCEEDED on stratum_bf

### ISSUE THREAD

**Issue by ccascone** [stratum/stratum#293]
**Describe the bug**
A gNMI-related thread seems to crash (or at least a crash-like stack trace is printed, see stratum.log) when ONOS issues a Get RPC to read interface counters. This happens consistently when restarting the stratum_bf container after ONOS has already established a first successful connection (including a pipeline push, interface discovery, etc).

[stratum.log](https://github.com/stratum/stratum/files/4916840/stratum.log)
[chassis-config.pb.txt](https://github.com/stratum/stratum/files/4916844/stratum-leaf1-chassis-config.pb.txt)
[onos-grpc.log](https://github.com/stratum/stratum/files/4916848/onos-grpc.log) (look for `callId=1300` for an example of Get RPC that fails)

**Environment**
latest `stratumproject/stratum-bf:9.0.0-4.14.49-OpenNetworkLinux` container on Wedge 100BF-32X execute with:

    CHASSIS_CONFIG=/root/chassis_config.pb.txt ./start-stratum-container.sh --bf-sim

Switch:
```bash
root@aether-tofino:~# cat /etc/onl/platform
x86-64-accton-wedge100bf-65x-r0
root@aether-tofino:~# uname -a
Linux aether-tofino 4.14.49-OpenNetworkLinux #1 SMP Thu Jun 25 17:42:47 UTC 2020 x86_64 GNU/Linux
root@aether-tofino:~# lsmod
Module                  Size  Used by
bf_kdrv                28672  2
x86_pkg_temp_thermal    16384  0
gpio_ich               16384  0
```

**To Reproduce**
Restart the Stratum container after ONOS has already connected to it once.

**Expected behavior**
The Get RPC should be completed successfully instead of a DEADLINE_EXCEEDED exception.

**Comment by Yi-Tseng** [comment]
I believed that this line causes the issue.
https://github.com/stratum/stratum/pull/178/files#diff-c4a583ef9a466f4a5199f2fe94500d9fR150

Currently, we remove all nodes and rebuild the gNMI path tree when we push a new gNMI config. 
However, every gNMI set also pushes a new (modified) config to the tree.

Few things we need to do to solve this issue.
1. Make sure no one can change the tree if anyone is trying to visiting tree nodes (add lock)
2. Removes node which we don't need instead of rebuild entire the tree
3. Unregister the `on_change_functor`(for gNMI subscription) correctly

The temporary solution is to remove that line. But we won't be able to `remove` tree nodes if we push a new chassis config manually.

**Comment by Yi-Tseng** [comment]
To reproduce the issue with gnmi-cli
start stratum on the switch
strat gnmi-cli which sampling counter values
`docker run --rm stratumproject/gnmi-cli --grpc-addr 10.128.13.223:28000 sub-sample /interfaces/interface[name=1/0]/state/counters --interval 500`

use another gnmi-cli to set a value to a specific tree node (e.g., enable/disable port)
`docker run stratumproject/gnmi-cli set --grpc-addr 10.128.13.223:28000 --bool-val=true /interfaces/interface[name=1/0]/config/enabled`

The output from the first gnmi-cli will change to different leaf nodes(should not happen), and stratum will crash after multiple gNMI set-request sent.
