### ISSUE TITLE
Problems installing kernel modules when trying to run stratum in Broadcom Tomahawk virtual device

### ISSUE THREAD

**Issue by sergio-gimenez** [stratum/stratum#86]
I am trying to build and run stratum on the Broadcom Tomahawk switch by following these [instructions](https://github.com/stratum/stratum/blob/master/stratum/hal/bin/bcm/standalone/README.md).
 I am using a VM with *Ubuntu 16.04* provided by Broadcom ([link](https://broadcom.ent.box.com/v/NCS-Community-June-2019)).
Everything works fine when building the Stratum binary. But I have problems installing dependencies to run the pre-built binaries for the kernel, specifically the kernel modules "linux_ngbde.ko" and "linux_ngknet.ko". When I try to install these I got the following error:

```
insmod: ERROR: could not insert module linux_ngbde.ko: Invalid module format
```

Which is probably related to the mismatch regarding the kernel version (the VM in use has kernel version "4.15.0-72" and the binaries require "4.14.49"). So I downgraded the kernel to the expected version ("4.14.49"), using an Ubuntu 18.04 VM. However, I get the same "insmod" error message when installing the "ngbde" and "ngknet" kernel modules.

Any ideas about how to fix this issue? Maybe you could provide an exhaustive list with the specific environment to use and changes to perform; or share the environment you used so that it has the pre-installed dependencies to compile and run stratum for Broadcom? Maybe I'm just missing something else?

Hope you can help with this.

Thanks in advance.

**EDIT:** Updated the title to be more consistent with the environment we are using

**Comment by pudelkoM** [comment]
I just updated the bcm [README](https://github.com/stratum/stratum/blob/update-bcm-readme/stratum/hal/bin/bcm/standalone/README.md). Can you verify your setup against it?

**Comment by pudelkoM** [comment]
I now realize we're talking about different use cases.

> Are the README/stratum_bcm instructions here aimed towards running Stratum with a Broadcom virtualized device?

No. `stratum_bcm` generally refers to the binary for *physical* switches. We currently do not support any **Broadcom** simulator. But read next point.

> Alternatively, is there a virtual built-in environment to test Stratum; as in the case of bmv2-stratum-p4runtime?

Yes, as listed in the [supported devices list](https://github.com/stratum/stratum#supported-devices), there is the bmv2 software switch. Same north-bound APIs (P4RT, ...), but runs on Linux with veth interfaces. [README](https://github.com/stratum/stratum/blob/master/stratum/hal/bin/bmv2/README.md)

> Tomahawk device simulation. Available from the Demo App in the SDKLT repo.

I knew this exists, but we never really looked at this in detail, because getting to run on real hardware was more important and we have bmv2 for the software side. But for the future this might be an interesting option for testing.


Unless you want to run `stratum_bcm` on a physical Tomahawk switch, your departing into uncharted territory where we have little experience.  Doesn't mean we will not help you, just saying that we have not explored much into that direction.

**Comment by CarolinaFernandez** [comment]
> I knew this exists, but we never really looked at this in detail, because getting to run on real hardware was more important and we have bmv2 for the software side. But for the future this might be an interesting option for testing.

That makes sense, considering P4 started as the main target and there are more resources for its virtual switch. Sergio had already worked with a P4-bmv2/Stratum environment for virtual switches and it worked well -- we hoped it would be the same for NPL/Broadcom; but since not, we will wait to get our hands on the physical switch before trying the ONIE 🡆 ONLPv2 🡆 Stratum installation.

Thanks for the help so far.
_(If @sergio-gimenez agrees, we can close the issue.)_
